/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import view.con.*;
import view.cad.*;
import view.edit.*;
import view.rem.*;
import model.Funcionario;

/**
 *
 * @author csouza
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Menu() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/view/img/logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLocacao = new javax.swing.JButton();
        btnDevolucao = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logado = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        conMenu = new javax.swing.JMenu();
        conCliente = new javax.swing.JMenuItem();
        conCategoria = new javax.swing.JMenuItem();
        conFilme = new javax.swing.JMenuItem();
        conDVD = new javax.swing.JMenuItem();
        conFunc = new javax.swing.JMenuItem();
        cadMenu = new javax.swing.JMenu();
        cadCliente = new javax.swing.JMenuItem();
        cadCategoria = new javax.swing.JMenuItem();
        cadFilme = new javax.swing.JMenuItem();
        cadDvd = new javax.swing.JMenuItem();
        cadFunc = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        editCliente = new javax.swing.JMenuItem();
        editCategoria = new javax.swing.JMenuItem();
        editFilme = new javax.swing.JMenuItem();
        editDVD = new javax.swing.JMenuItem();
        editFunc = new javax.swing.JMenuItem();
        remMenu = new javax.swing.JMenu();
        remCliente = new javax.swing.JMenuItem();
        remCategoria = new javax.swing.JMenuItem();
        remFilme = new javax.swing.JMenuItem();
        remDVD = new javax.swing.JMenuItem();
        remFunc = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Video Locadora - Menu Principal");
        setResizable(false);

        btnLocacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/loc.png"))); // NOI18N
        btnLocacao.setText("Locação");
        btnLocacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnDevolucao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/dev.png"))); // NOI18N
        btnDevolucao.setText("Devolução");
        btnDevolucao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/exit.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Desenvolvido por: Android'z Engenharia de Software LTDA");

        logado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/logado.png"))); // NOI18N

        conMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/search.png"))); // NOI18N
        conMenu.setText("Consultar");
        conMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        conCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/user-search.png"))); // NOI18N
        conCliente.setText("Cliente");
        conCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        conCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conClienteActionPerformed(evt);
            }
        });
        conMenu.add(conCliente);

        conCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/category.png"))); // NOI18N
        conCategoria.setText("Categoria");
        conCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        conCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conCategoriaActionPerformed(evt);
            }
        });
        conMenu.add(conCategoria);

        conFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/movie.png"))); // NOI18N
        conFilme.setText("Filme");
        conFilme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        conFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conFilmeActionPerformed(evt);
            }
        });
        conMenu.add(conFilme);

        conDVD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/dvd.png"))); // NOI18N
        conDVD.setText("DVD");
        conDVD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        conDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conDVDActionPerformed(evt);
            }
        });
        conMenu.add(conDVD);

        conFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/func.png"))); // NOI18N
        conFunc.setText("Funcionário");
        conFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        conFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conFuncActionPerformed(evt);
            }
        });
        conMenu.add(conFunc);
        conFunc.getAccessibleContext().setAccessibleDescription("");

        menu.add(conMenu);

        cadMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/add.png"))); // NOI18N
        cadMenu.setText("Cadastrar");
        cadMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/user-add.png"))); // NOI18N
        cadCliente.setText("Cliente");
        cadCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadClienteActionPerformed(evt);
            }
        });
        cadMenu.add(cadCliente);

        cadCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/category-add.png"))); // NOI18N
        cadCategoria.setText("Categoria");
        cadCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCategoriaActionPerformed(evt);
            }
        });
        cadMenu.add(cadCategoria);

        cadFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/movie.png"))); // NOI18N
        cadFilme.setText("Filme");
        cadFilme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFilmeActionPerformed(evt);
            }
        });
        cadMenu.add(cadFilme);

        cadDvd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/dvd.png"))); // NOI18N
        cadDvd.setText("DVD");
        cadDvd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadDvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadDvdActionPerformed(evt);
            }
        });
        cadMenu.add(cadDvd);

        cadFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/func.png"))); // NOI18N
        cadFunc.setText("Funcionário");
        cadFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFuncActionPerformed(evt);
            }
        });
        cadMenu.add(cadFunc);

        menu.add(cadMenu);

        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/edit.png"))); // NOI18N
        editMenu.setText("Editar");
        editMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        editCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/user-edit.png"))); // NOI18N
        editCliente.setText("Cliente");
        editCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editMenu.add(editCliente);

        editCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/category-edit.png"))); // NOI18N
        editCategoria.setText("Categoria");
        editCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editMenu.add(editCategoria);

        editFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/movie.png"))); // NOI18N
        editFilme.setText("Filme");
        editFilme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editMenu.add(editFilme);

        editDVD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/dvd.png"))); // NOI18N
        editDVD.setText("DVD");
        editDVD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editMenu.add(editDVD);

        editFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/func.png"))); // NOI18N
        editFunc.setText("Funcionário");
        editMenu.add(editFunc);

        menu.add(editMenu);

        remMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/remove.png"))); // NOI18N
        remMenu.setText("Excluir");
        remMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        remCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/user-rem.png"))); // NOI18N
        remCliente.setText("Cliente");
        remCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remMenu.add(remCliente);

        remCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/category-remove.png"))); // NOI18N
        remCategoria.setText("Categoria");
        remCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remMenu.add(remCategoria);

        remFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/movie.png"))); // NOI18N
        remFilme.setText("Filme");
        remFilme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remMenu.add(remFilme);

        remDVD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/dvd.png"))); // NOI18N
        remDVD.setText("DVD");
        remDVD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remMenu.add(remDVD);

        remFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/menu/func.png"))); // NOI18N
        remFunc.setText("Funcionário");
        remFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remMenu.add(remFunc);

        menu.add(remMenu);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logado))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(37, Short.MAX_VALUE)
                        .addComponent(btnLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(btnDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conDVDActionPerformed
        new ConDvd().setVisible(true);
    }//GEN-LAST:event_conDVDActionPerformed

    private void conClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conClienteActionPerformed
        new ConCliente().setVisible(true);
    }//GEN-LAST:event_conClienteActionPerformed

    private void conCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conCategoriaActionPerformed
        new ConCategoria().setVisible(true);
    }//GEN-LAST:event_conCategoriaActionPerformed

    private void conFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conFilmeActionPerformed
        new ConFilme().setVisible(true);
    }//GEN-LAST:event_conFilmeActionPerformed

    private void conFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conFuncActionPerformed
        new ConFunc().setVisible(true);
    }//GEN-LAST:event_conFuncActionPerformed

    private void cadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadClienteActionPerformed
        new CadCliente().setVisible(true);
    }//GEN-LAST:event_cadClienteActionPerformed

    private void cadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCategoriaActionPerformed
        new CadCategoria().setVisible(true);
    }//GEN-LAST:event_cadCategoriaActionPerformed

    private void cadFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFilmeActionPerformed
        new CadFilme().setVisible(true);
    }//GEN-LAST:event_cadFilmeActionPerformed

    private void cadDvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadDvdActionPerformed
        new CadDvd().setVisible(true);
    }//GEN-LAST:event_cadDvdActionPerformed

    private void cadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFuncActionPerformed
        new CadFunc().setVisible(true);
    }//GEN-LAST:event_cadFuncActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    private void esconderMenus(){
        conFunc.setVisible(false);
        cadFunc.setVisible(false);
        editFunc.setVisible(false);
        remFunc.setVisible(false);
    }
    private void mostrarMenus(){
        conFunc.setVisible(true);
        cadFunc.setVisible(true);
        editFunc.setVisible(true);
        remFunc.setVisible(true);
    }
    public void nomeFuncionario(Funcionario func){
        logado.setText(func.getNome());
        if(func.getNome().equalsIgnoreCase("Clemilton")){
            mostrarMenus();
        }else{
            esconderMenus();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolucao;
    private javax.swing.JButton btnLocacao;
    private javax.swing.JButton btnLogout;
    private javax.swing.JMenuItem cadCategoria;
    private javax.swing.JMenuItem cadCliente;
    private javax.swing.JMenuItem cadDvd;
    private javax.swing.JMenuItem cadFilme;
    private javax.swing.JMenuItem cadFunc;
    private javax.swing.JMenu cadMenu;
    private javax.swing.JMenuItem conCategoria;
    private javax.swing.JMenuItem conCliente;
    private javax.swing.JMenuItem conDVD;
    private javax.swing.JMenuItem conFilme;
    private javax.swing.JMenuItem conFunc;
    private javax.swing.JMenu conMenu;
    private javax.swing.JMenuItem editCategoria;
    private javax.swing.JMenuItem editCliente;
    private javax.swing.JMenuItem editDVD;
    private javax.swing.JMenuItem editFilme;
    private javax.swing.JMenuItem editFunc;
    private javax.swing.JMenu editMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logado;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem remCategoria;
    private javax.swing.JMenuItem remCliente;
    private javax.swing.JMenuItem remDVD;
    private javax.swing.JMenuItem remFilme;
    private javax.swing.JMenuItem remFunc;
    private javax.swing.JMenu remMenu;
    // End of variables declaration//GEN-END:variables
}
